
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimal-deployment
  labels:
    app: minimal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimal
  template:
    metadata:
      labels:
        app: minimal
    spec:
      containers:
        - name: minimal
          image: maxmcd/tcp-proxy
          command: ["tcp-proxy"]
          args: ["-l", "0.0.0.0:8080", "-r", "minimal-extname-service:{localPort}"]
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: minimal-extname-service
spec:
  type: ExternalName
  externalName: host.docker.internal
